# Generated by Django 2.2.12 on 2021-11-12 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211112_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 11, 26, 161323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 11, 26, 162492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 11, 26, 161687, tzinfo=utc)),
        ),
    ]
