# Generated by Django 2.2.12 on 2021-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
    ]
